/**
 * Embedded BMAD-format templates and rules.
 * Logic dependency on BMAD-METHOD — no external skill files required.
 */

export const BMAD_RULES = {
  prdSections: [
    "Executive Summary",
    "Problem Statement",
    "Goals & Success Metrics",
    "User Personas",
    "Functional Requirements",
    "Non-Functional Requirements",
    "Out of Scope",
    "Open Questions",
  ],
  userStoryFormat: "As a {role}, I want {action}, so that {benefit}.",
  acceptanceCriteriaFormat: "Given {context}, When {action}, Then {outcome}.",
  storyPriority: ["P0", "P1", "P2", "P3"],
} as const;

export function buildPrd(requirement: string, projectSlug: string): string {
  const date = new Date().toISOString().slice(0, 10);
  return `# Product Requirements Document: ${projectSlug}

> Generated by bmad-workflow-mcp | BMAD format | ${date}

## Executive Summary

${requirement}

## Problem Statement

Users need a solution that addresses: ${requirement}

## Goals & Success Metrics

| Goal | Metric | Target |
|------|--------|--------|
| Deliver core capability | Feature completion | 100% MVP scope |
| Quality | Defect rate post-release | < 5 critical bugs |
| Usability | Task success rate | ≥ 90% |

## User Personas

### Primary User
- **Role**: End user / developer
- **Need**: ${requirement}
- **Pain**: Manual, inconsistent workflow without structured planning

## Functional Requirements

### FR-1: Core Feature
- **Description**: Implement capability derived from requirement
- **Source**: User requirement input
- **Priority**: P0

### FR-2: Workflow Artifacts
- **Description**: Produce BMAD-aligned planning artifacts (PRD, stories, AC, architecture, tasks)
- **Priority**: P0

## Non-Functional Requirements

- **Performance**: Planning artifacts generated within seconds
- **Maintainability**: Markdown artifacts, version-control friendly
- **Traceability**: Each story links back to FR IDs

## Out of Scope

- Production deployment automation (unless explicitly requested)
- Third-party integrations not mentioned in requirement

## Open Questions

- [ ] Confirm target tech stack with stakeholder
- [ ] Confirm MVP vs full scope boundary
`;
}

export function buildUserStories(requirement: string, prdExcerpt: string): string {
  return `# User Stories

> BMAD User Story Format | Derived from PRD

## Epic 1: ${requirement.slice(0, 80)}

### Story 1.1 — Core capability

**User Story**
As a **product owner**, I want **the system to address: ${requirement}**, so that **users achieve their goal with minimal friction**.

**Priority**: P0  
**FR Trace**: FR-1

**Notes**
${prdExcerpt.slice(0, 300)}

---

### Story 1.2 — Planning artifacts

**User Story**
As a **developer**, I want **structured BMAD planning documents**, so that **implementation follows a clear, auditable plan**.

**Priority**: P1  
**FR Trace**: FR-2

---

### Story 1.3 — Validation & quality

**User Story**
As a **QA engineer**, I want **acceptance criteria in BDD format**, so that **each story can be verified objectively**.

**Priority**: P1  
**FR Trace**: FR-1
`;
}

export function buildAcceptanceCriteria(): string {
  return `# Acceptance Criteria

> BDD Format (Given / When / Then) per BMAD-METHOD

## Story 1.1 — Core capability

### AC-1.1.1
**Given** the requirement has been captured in the PRD  
**When** the development team implements the core feature  
**Then** the feature satisfies FR-1 as described in the PRD

### AC-1.1.2
**Given** a user with valid access  
**When** they use the primary workflow  
**Then** the expected outcome is achieved without errors

---

## Story 1.2 — Planning artifacts

### AC-1.2.1
**Given** a completed workflow run  
**When** artifacts are inspected under \`.bmad-output/\`  
**Then** PRD, user stories, architecture, and tasks files exist

---

## Story 1.3 — Validation & quality

### AC-1.3.1
**Given** acceptance criteria for a story  
**When** verification is performed  
**Then** each AC can be marked pass/fail with evidence
`;
}

export function buildArchitecture(requirement: string): string {
  return `# Architecture Design Recommendations

> BMAD Planning Artifact | ${new Date().toISOString().slice(0, 10)}

## Context

Requirement: ${requirement}

## Option A — Monolithic Application (Recommended for MVP)

| Aspect | Choice |
|--------|--------|
| Frontend | React / Vue / vanilla per project |
| Backend | Node.js or Python API |
| Storage | PostgreSQL or SQLite |
| Pros | Fast to build, simple deploy |
| Cons | Scaling limits later |

## Option B — Modular Monolith

| Aspect | Choice |
|--------|--------|
| Structure | Domain modules with clear boundaries |
| Pros | Easier evolution to microservices |
| Cons | More upfront design |

## Option C — Serverless / Edge

| Aspect | Choice |
|--------|--------|
| Compute | Cloud functions |
| Pros | Pay-per-use, auto-scale |
| Cons | Cold start, vendor lock-in |

## Recommendation

Start with **Option A** unless non-functional requirements demand distributed architecture.

## Key Components

1. **API Layer** — REST or RPC endpoints
2. **Domain Layer** — Business rules from user stories
3. **Persistence** — Entity storage per FR mapping
4. **Integration** — External services as needed

## Risks

| Risk | Mitigation |
|------|------------|
| Scope creep | Strict MVP from PRD Out of Scope |
| Tech debt | Follow task breakdown sprint boundaries |
`;
}

export function buildTasks(): string {
  return `# Development Task Breakdown

> Sprint-ready tasks linked to user stories

## Story 1.1 — Core capability

| ID | Task | Estimate | Depends |
|----|------|----------|---------|
| T-1.1.1 | Parse requirement & confirm scope | 2h | — |
| T-1.1.2 | Implement core domain logic | 8h | T-1.1.1 |
| T-1.1.3 | Add API / UI entry points | 6h | T-1.1.2 |
| T-1.1.4 | Unit tests for core paths | 4h | T-1.1.2 |

## Story 1.2 — Planning artifacts

| ID | Task | Estimate | Depends |
|----|------|----------|---------|
| T-1.2.1 | Wire artifact output paths | 2h | — |
| T-1.2.2 | Validate BMAD format compliance | 2h | T-1.2.1 |

## Story 1.3 — Validation & quality

| ID | Task | Estimate | Depends |
|----|------|----------|---------|
| T-1.3.1 | Map AC to test cases | 3h | T-1.1.4 |
| T-1.3.2 | Integration test skeleton | 4h | T-1.1.3 |

## Definition of Done

- [ ] All P0 tasks complete
- [ ] AC verified with evidence
- [ ] Lint / tests pass (if applicable)
`;
}

export function buildCodeSkeleton(projectSlug: string): string {
  return `# Code Skeleton: ${projectSlug}

> Placeholder generated by bmad-workflow-mcp — replace with real implementation

## Suggested Structure

\`\`\`
src/
├── index.ts          # Entry point
├── domain/           # Business logic
├── api/              # HTTP handlers
└── types.ts          # Shared types
\`\`\`

## Next Steps

1. Scaffold project with chosen stack from architecture doc
2. Implement tasks T-1.1.x in order
3. Run tests and lint before code review step
`;
}

export function buildCodeReviewPlaceholder(lintOutput?: string): string {
  return `# Code Review Report

> ${lintOutput ? "Lint executed" : "Placeholder — enable code review or run lint manually"}

## Summary

| Check | Status |
|-------|--------|
| Lint | ${lintOutput ? "Executed" : "Skipped (no lint script)"} |
| Unit tests | Manual verification required |
| AC coverage | See 03-acceptance-criteria.md |

## Lint Output

\`\`\`
${lintOutput ?? "(no lint output — project may lack npm run lint)"}
\`\`\`

## Review Notes

- Verify all P0 acceptance criteria before merge
- Ensure traceability from PRD → stories → tasks
`;
}

export function buildFinalReport(state: {
  workflowId: string;
  workflowType: "planning" | "pipeline";
  requirementDescription: string;
  completedSteps: string[];
  skippedSteps: string[];
  totalDurationMs: number;
  totalTokens: number;
  outputDir: string;
  mode: string;
  batchName?: string;
  lastError?: string;
}): string {
  return `# BMAD Workflow Final Report

| Field | Value |
|-------|-------|
| Workflow ID | ${state.workflowId} |
| Workflow Type | ${state.workflowType} |
| Mode | ${state.mode} |
| Output Directory | ${state.outputDir} |
| Batch | ${state.batchName ?? "n/a"} |
| Total Duration | ${Math.round(state.totalDurationMs / 1000)}s |
| Token Estimate | ~${state.totalTokens} |

## Requirement

${state.requirementDescription}

## Completed Steps

${state.completedSteps.map((s) => `- ✅ ${s}`).join("\n") || "- (none)"}

## Skipped Steps

${state.skippedSteps.map((s) => `- ⏭ ${s}`).join("\n") || "- (none)"}

## Artifacts

See output directory for generated planning/pipeline artifacts.

${state.lastError ? `## Last Error\n\n${state.lastError}` : ""}

---
*Generated by @huhai0403/bmad-workflow-mcp*
`;
}
